<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Momo</AssemblyName>
    <RootNamespace>Momo</RootNamespace>
    <Version>2.1.1</Version>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <DefaultItemExcludes>$(DefaultItemExcludes);artifacts\**;dist\**</DefaultItemExcludes>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>assets\momo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="assets\**\*;licenses\**\*;docs\**\*;README.md;LICENSE">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
